// <auto-generated />
using System;
using GiftShop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftShop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608000001_MakeCategoryIdNullable")]
    partial class MakeCategoryIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftShop.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(240).HasColumnType("character varying(240)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Categories", "public");
                });

            modelBuilder.Entity("GiftShop.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("CategoryId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("ShortDescription").HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<string>("Title").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Products", "public");
                });

            modelBuilder.Entity("GiftShop.Domain.Entities.SiteContentItem", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AltText").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<byte[]>("BinaryValue").HasColumnType("bytea");
                    b.Property<string>("ContentKey").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DisplayLocation").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Kind").IsRequired().HasColumnType("text");
                    b.Property<string>("MimeType").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("SectionName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<string>("TextValue").HasMaxLength(600).HasColumnType("character varying(600)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ContentKey").IsUnique();
                    b.ToTable("SiteContentItems", "public");
                });

            modelBuilder.Entity("GiftShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("GiftShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Category");
                });

            modelBuilder.Entity("GiftShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}